# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d194962edc9f8813848a1c954a5037a8460577d661861483a6c6a7f869224e66012e8f2b74340d9fea850fa25bf19ae9defc69c85aa397fcb3a6cea93e54366

test:
  secret_key_base: b0c0e14952fb3abc1d6aab316a9355ebc7e2c962d88494e35a977c12ce19ec0fdccf6f4c1e2d27d9b79502d2f87eaea2cb561ec966443bfae9f2460f24278ed2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
